'https://www.youtube.com/channel/UCHm9SiOLG8UoBT8STWY5mVA/videos',\
'https://www.youtube.com/channel/UCTQ-gSOpuLtgQarXw3XVmyQ/videos',\
'https://www.youtube.com/channel/UCXpxKdZAiyUEaTkoCPpEZzg/videos',\
'https://www.youtube.com/channel/UCA2qvunXtkK3SUVxfOGiobA/videos',\
'https://www.youtube.com/channel/UC6FcYHEm7SO1jpu5TKjNXEA/videos',\
'https://www.youtube.com/channel/UCTMt7iMWa7jy0fNXIktwyLA/videos',\
'https://www.youtube.com/channel/UCPcF3KTqhD67ADkukx_OeDg/videos',\
'https://www.youtube.com/channel/UCI7ktPB6toqucpkkCiolwLg/videos',\
'https://www.youtube.com/channel/UCX9VHpN62jkqCCntHxymPOA/videos',\
'https://www.youtube.com/channel/UCrLO-yoAu4ZTzRSdmWqS53A/videos',\
'https://www.youtube.com/user/babybus1000/featured/videos',\
'https://www.youtube.com/c/charlie615119/videos',\
'https://www.youtube.com/channel/UC5l1Yto5oOIgRXlI4p4VKbw/videos',\
'https://www.youtube.com/c/RayDuEnglish/videos',\
'https://www.youtube.com/channel/UC77tdTDovSm70lFOkn9398Q/videos',\
'https://www.youtube.com/user/binmusictaipei/videos',\
'https://www.youtube.com/c/MashaBearCH/videos',\
'https://www.youtube.com/c/ettvCTime/videos',\
'https://www.youtube.com/results?search_query=%E8%94%A1%E9%98%BF%E5%98%8E/videos',\
'https://www.youtube.com/c/jaychou/videos/videos',\
'https://www.youtube.com/c/JoemanStarCraft/videos',\
'https://www.youtube.com/c/%E6%9C%A8%E6%9B%9C4%E8%B6%85%E7%8E%A9/videos',\
'https://www.youtube.com/channel/UC3LBFXbWtEBdOOUb8-qJm9Q/videos',\
'https://www.youtube.com/c/RusPiano/videos',\
'https://www.youtube.com/c/HuashiRomance/videos',\
'https://www.youtube.com/c/amogood/videos',\
'https://www.youtube.com/channel/UCIU8ha-NHmLjtUwU7dFiXUA/videos',\
'https://www.youtube.com/c/TVBSNEWS01/videos',\
'https://www.youtube.com/c/%E9%BB%83%E6%B0%8F%E5%85%84%E5%BC%9F/videos',\
'https://www.youtube.com/c/DEJunMix/videos',\
'https://www.youtube.com/c/LinfairRecords/videos',\
'https://www.youtube.com/c/Chienseating/videos',\
'https://www.youtube.com/c/newsebc/videos',\
'https://www.youtube.com/c/%E4%B8%AD%E5%A4%A9%E6%96%B0%E8%81%9ECH52/videos',\
'https://www.youtube.com/c/LucasandKibo/videos',\
'https://www.youtube.com/user/KEVIN0204660/videos',\
'https://www.youtube.com/c/warnertaiwan/videos',\
'https://www.youtube.com/c/%E8%94%A1%E9%98%BF%E5%98%8ELife/videos',\
'https://www.youtube.com/c/%E7%99%BD%E7%99%A1%E5%85%AC%E4%B8%BB/videos',\
'https://www.youtube.com/c/%E7%B6%9C%E8%97%9D%E7%8E%A9%E5%BE%88%E5%A4%A7MrPlayer/featured/videos',\
'https://www.youtube.com/user/HIMservice/videos',\
'https://www.youtube.com/c/masaabc1/videos',\
'https://www.youtube.com/c/chuchushoeTW/videos',\
'https://www.youtube.com/c/TaiwanTalentShow/videos',\
'https://www.youtube.com/channel/UCgdwtyqBunlRb-i-7PnCssQ/videos',\
'https://www.youtube.com/c/STRNetworkasia/videos',\
'https://www.youtube.com/c/%E4%BA%AE%E7%94%9F%E6%B4%BBBrightSide/videos',\
'https://www.youtube.com/c/TerryFilms2019/videos',\
'https://www.youtube.com/c/SanyuanJAPAN2015/videos',\
'https://www.youtube.com/c/anjouclever103/videos',\
'https://www.youtube.com/channel/UCnfPDcASesYjcO5u-ELnb-Q/videos',\
'https://www.youtube.com/channel/UCGpNjY0Xq2GJLXh4OOX1LOA/videos',\
'https://www.youtube.com/user/jasonjason1124/videos',\
'https://www.youtube.com/c/yoyotvebc/videos',\
'https://www.youtube.com/channel/UC24h-JBUHXT5HXIK_9cWOmQ/videos',\
'https://www.youtube.com/c/%E4%BA%BA%E7%94%9F%E8%82%A5%E5%AE%85x%E5%B0%8A/videos',\
'https://www.youtube.com/user/13foreverandever/videos',\
'https://www.youtube.com/c/FTVDRAMA/videos',\
'https://www.youtube.com/channel/UCIdhd_1spj49unBWx1fjS2A/videos',\
'https://www.youtube.com/c/%E5%A2%A8%E9%8F%A1%E5%93%A5%E5%AF%A6%E6%B3%81TV/videos',\
'https://www.youtube.com/channel/UCcb9uxCoIgw7RQjQnlgd0Xw/videos',\
'https://www.youtube.com/user/d59025/videos',\
'https://www.youtube.com/c/%E6%90%9E%E7%A5%9E%E9%A6%AC/videos',\
'https://www.youtube.com/user/louislee0602/videos',\
'https://www.youtube.com/c/andchinablue500walkerdad/videos',\
'https://www.youtube.com/c/RSPannie72127/videos',\
'https://www.youtube.com/channel/UCzxN4G3s9uR9ao5_O5DoXmA/videos',\
'https://www.youtube.com/c/ZyNXyZ/videos',\
'https://www.youtube.com/user/SETShowBiz/videos',\
'https://www.youtube.com/user/TheLiuPei/videos',\
'https://www.youtube.com/c/LukeMartin/videos',\
'https://www.youtube.com/c/%E4%B8%AD%E6%99%82%E6%96%B0%E8%81%9E%E7%B6%B2/videos',\
'https://www.youtube.com/c/%E6%88%91%E6%84%9B%E5%A4%A7%E7%86%B1%E9%96%80/videos',\
'https://www.youtube.com/c/Kusdream%E9%85%B7%E7%9A%84%E5%A4%A2/videos',\
'https://www.youtube.com/c/liketaitai/videos',\
'https://www.youtube.com/channel/UCTqPBBnP2T57kmiPQ87986g/videos',\
'https://www.youtube.com/c/oeurxhichocolate/videos',\
'https://www.youtube.com/channel/UC8zkK0-g8S8Z_t8ZjUmpAlA/videos',\
'https://www.youtube.com/c/%E9%A4%A8%E9%95%B7%E6%88%90%E5%90%89%E6%80%9D%E6%B1%97/videos',\
'https://www.youtube.com/channel/UCZVCbj9weVNAWqXS9gnfm5A/videos',\
'https://www.youtube.com/channel/UCAfcy122TZHqDQMMAwfbvBQ/videos',\
'https://www.youtube.com/c/ggukim/videos',\
'https://www.youtube.com/c/EBCbuzz/videos',\
'https://www.youtube.com/c/%E5%B0%91%E5%BA%B7%E6%88%B0%E6%83%85%E5%AE%A4/videos',\
'https://www.youtube.com/user/NGCTaiwan/videos',\
'https://www.youtube.com/c/%E6%88%91%E6%84%9B%E5%BA%B7%E7%86%99/videos',\
'https://www.youtube.com/channel/UCOf3OYchR7r7FjkIhD949rA/videos',\
'https://www.youtube.com/c/NyoNyoTV/videos',\
'https://www.youtube.com/c/papayaclass/videos',\
'https://www.youtube.com/channel/UC_dXxZgHNpNVElF6y4P10Rw/videos',\
'https://www.youtube.com/c/HelloCatie/videos',\
'https://www.youtube.com/user/TWnineoneone911/videos',\
'https://www.youtube.com/user/MrChesterccj/videos',\
'https://www.youtube.com/c/dan201/videos',\
'https://www.youtube.com/c/VSMediatw/videos',\
'https://www.youtube.com/c/counter656/videos',\
'https://www.youtube.com/c/TaiwanBar/videos',\
'https://www.youtube.com/user/Stopkiddinstudio/videos',\
'https://www.youtube.com/c/%E5%81%A5%E5%BA%B720health20/featured/videos',\
'https://www.youtube.com/c/%E5%90%AB%E7%BE%9E%E8%8D%89MIMOSAGO/videos',\
'https://www.youtube.com/channel/UCw2W7GIqJNB-UMUxncnMuiw/videos',\