# Generated by Django 3.2.12 on 2022-02-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='youtuber',
            fields=[
                ('url', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('youtuber_type', models.CharField(max_length=20)),
                ('icon', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='video_info',
            fields=[
                ('url', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.FloatField(default=0.0)),
                ('icon', models.CharField(default='', max_length=200)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linebotapp.youtuber')),
            ],
        ),
        migrations.CreateModel(
            name='user_videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linebotapp.user_info')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linebotapp.video_info')),
            ],
        ),
        migrations.AddField(
            model_name='user_info',
            name='channel',
            field=models.ManyToManyField(through='linebotapp.user_channel', to='linebotapp.youtuber'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='videos',
            field=models.ManyToManyField(through='linebotapp.user_videos', to='linebotapp.video_info'),
        ),
        migrations.AddField(
            model_name='user_channel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linebotapp.youtuber'),
        ),
        migrations.AddField(
            model_name='user_channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linebotapp.user_info'),
        ),
    ]
