# Generated by Django 3.2.12 on 2022-02-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hot_video',
            fields=[
                ('url', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.FloatField(default=0.0)),
                ('icon', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
