"""
Django settings for youtube_linebot project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

#Irene token
LINE_CHANNEL_ACCESS_TOKEN = '*'
LINE_CHANNEL_SECRET = '*'
SECRET_KEY = '*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'linebotapp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'youtube_linebot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'template')],#新增temp;ate資料夾
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'youtube_linebot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql', #postgresql
#         'NAME': 'd7rqrbot9jdphg', #資料庫名稱
#         'USER':'cvyycoqolturzq', #資料庫帳號
#         'PASSWORD':'3d2686d07472f4f90309cfd61672c663195b7eb176cc848da37c6dab2c7d1731', #資料庫密碼
#         'HOST':'ec2-44-194-113-156.compute-1.amazonaws.com',
#         'PORT':'5432'
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql', #postgresql
#         'NAME': 'de8jai1l3rrdi5', #資料庫名稱
#         'USER':'zqcmpolgaejwtx', #資料庫帳號
#         'PASSWORD':'3ac2d1a73e87ece734cc70b5a72515a6496dc60e9236712b1376bc6379f5df47', #資料庫密碼
#         'HOST':'ec2-34-233-157-189.compute-1.amazonaws.com',
#         'PORT':'5432'
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', #postgresql
        'NAME': 'd4crf41rmge8ds', #資料庫名稱
        'USER':'vzkhdlccezxnep', #資料庫帳號
        'PASSWORD':'637dfcb124c91f2e45e56035d6147d01f7e7c710bcebd84e26491873642c4c4d', #資料庫密碼
        'HOST':'ec2-3-209-61-239.compute-1.amazonaws.com',
        'PORT':'5432'
    }
}
 
# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-hant' #繁體中文

TIME_ZONE = 'Asia/Taipei' #更改時區

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICILES_DIRS = [os.path.join(BASE_DIR,'static')] #加入static資料夾

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

django_heroku.settings(locals())
